### ISSUE TITLE
Support feh as wallpaper manager

### ISSUE THREAD

**Issue by rockneurotiko** [tsarjak/WallpapersFromReddit#10]
If you want to support more desktops than Gnome (I'm using awesome and didn't work), I recommend you that, if feh is detected, use feh to set the wallpaper with a command like this:

`os.system('feh --bg-fill "%s"' % listwallpaper[count])`

**Comment by tsarjak** [comment]
Alright, thanks! I'll try to add an option to install feh if it isn't already present! :)
