### ISSUE TITLE
Script looks ugly

### ISSUE THREAD

**Issue by nix-py** [tsarjak/WallpapersFromReddit#12]
Should I try to PEP8ify it

**Comment by tsarjak** [comment]
Sure, go ahead! :)

**Comment by nix-py** [comment]
Thanx. Should I also change variable names according to PEP8? PEP8 suggest variable names with `underscores`

**Comment by tsarjak** [comment]
Umm, alright. Could you try once without changing the variable names? I'll just add some comments in the code to make sure that change in names don't confuse me later!

**Comment by nix-py** [comment]
Yes sure

**Comment by tsarjak** [comment]
Thank you! :)

**Comment by tsarjak** [comment]
Check the code now!

**Comment by nix-py** [comment]
Yeah nice
