### ISSUE TITLE
Option -hq should not delete images from Wallpapers folder

### ISSUE THREAD

**Issue by joeytwiddle** [tsarjak/WallpapersFromReddit#24]
## Problem

It looks like this option will delete any low-res images from the Wallpapers folder, including any images which were already there, not downloaded by the script!

This may be an unexpected and unwanted surprise for someone who already had some small images in that folder.

## Solutions

The script could get the `listwallpaper` from the list of files that was downloaded, rather than polling the destination folder for all the files inside it.

Alternatively, the default folder could have a unique name, e.g. `$HOME/Wallpapers/WallpapersFromReddit` and the script could create the folder if it doesn't already exist.

**Comment by tsarjak** [comment]
Totally makes sense. Shouldn't be doing that. Hadn't seen this code in a long time. But have a look at the latest commits, I have revamped the code and fixed this issue.

Not sure what you mean by landscape and portrait options? Basically rotate it accordingly before saving?
